"""inscripcion_provisional

Revision ID: 9adfbcfa71fb
Revises: a1b2c3d4e5f6
Create Date: 2026-05-06 12:18:49.744781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9adfbcfa71fb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripcion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provisional', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('anio_reserva', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripcion', schema=None) as batch_op:
        batch_op.drop_column('anio_reserva')
        batch_op.drop_column('provisional')

    # ### end Alembic commands ###
